<?php
/**
 * Created by PhpStorm.
 * User: shiblie
 * Date: 11/8/16
 * Time: 5:46 AM
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;


class UserMaster extends Model {


	protected $table = 'usermaster';

	protected $fillable = [
        'acquired_date',
        'active',
        'address_title',
        'apartment',
        'area',
        'benefit_description',
        'benefit_name',
        'benefit_value',
        'birth_date',
        'birth_place',
        'building_name',
        'building_no',
        'business_email',
        'company',
        'country_origin',
        'degree',
        'dept_dept_no',
        'dept_emp_id',
        'dept_name',
        'doc_expiry_date',
        'doc_issue_date',
        'doc_issuer',
        'doc_loc',
        'doc_type',
        'document_country',
        'emergency_contact_name',
        'emergency_contact_number',
        'emp_ref',
        'exp_from_date',
        'exp_job_details',
        'exp_to_date',
        'experience_city',
        'father_name',
        'first_name',
        'gender',
        'grant_permission',
        'height',
        'interview_details',
        'interview_occurance_details',
        'interview_occurrred',
        'interview_result',
        'interview_schedule_date',
        'interview_schedule_notes',
        'interview_scheduled_by',
        'job_title',
        'joining_date',
        'landline1',
        'landline2',
        'landmark',
        'last_name',
        'layout_boxed',
        'layout_fixed',
        'leave_type',
        'leave_type_notes',
        'local_extension',
        'map_address_id',
        'map_appplicant_id',
        'mapdoc_applicant_id',
        'mapdoc_doc_id',
        'mapint_interview_id',
        'mapint_interviewer_id',
        'mapisch_int_schedule_id',
        'mapisch_interview_id',
        'maplvs_emp_id',
        'maplvs_from_date',
        'maplvs_to_date',
        'maprol_role_id',
        'maprol_user_id',
        'mapskl_applicant_id',
        'mapskl_skill_id',
        'mapttl_emp_id',
        'mapttl_from_date',
        'mapttl_title_id',
        'mapttl_to_date',
        'marital_status',
        'middle_name',
        'mobile1',
        'mobile2',
        'mother_name',
        'nationality',
        'notes',
        'permission_functions',
        'permission_module',
        'permission_title',
        'personal_email',
        'pobox',
        'primary_phone',
        'prof_pic',
        'religion',
        'rightbar_skin_dark',
        'rightbar_slide',
        'role_title',
        'salary',
        'salary_benefit_id',
        'salary_from_date',
        'salary_to_date',
        'sidebar_collapsed',
        'sidebar_hover_expand',
        'sidebar_mini',
        'skill_desc',
        'skill_name',
        'source',
        'street_name',
        'street_no',
        'tbladr_city_id',
        'tbldgr_acquired_city',
        'tbldgr_acquired_from',
        'tblint_interview_date',
        'tbllvt_leave_type',
        'tblttl_title_desc',
        'theme_color',
        'title',
        'u_id',
        'username',
        'visa_expiry_date',
        'visa_file_number',
        'visa_issue_date',
        'visa_sponsor',
        'visa_type',
        'weight',
	];


}
